name: PianoPlugin
version: ${project.version}
main: hse.minecraft.pianoplugin.PianoPlugin
commands:
  menu:
    description: show piano or playlist inventory panel
  plays:
    description: play sound from minecraft from Enum Sound
    usage: /plays [name]