name: PianoPlugin
version: ${project.version}
main: hse.minecraft.pianoplugin.PianoPlugin
commands:
  piano:
    description: show piano inventory panel
  plays:
    description: play sound from minecraft from Enum Sound